package com.intelgy.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-09-06T17:01:33.517-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://services.intelgy.com", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://services.intelgy.com")
    @WebResult(name = "outputSOATest", targetNamespace = "http://services.intelgy.com", partName = "out")
    public OutputSOATest soaTest(
        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://services.intelgy.com")
        InputSOATest in
    );
}
