package com.intelgy.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-11-07T11:28:58.591-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://services.intelgy.com/", name = "TestWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebService {

    @WebMethod
    @RequestWrapper(localName = "doTest", targetNamespace = "http://services.intelgy.com/", className = "com.intelgy.services.DoTest")
    @ResponseWrapper(localName = "doTestResponse", targetNamespace = "http://services.intelgy.com/", className = "com.intelgy.services.DoTestResponse")
    public void doTest(
        @WebParam(name = "testInput", targetNamespace = "")
        com.intelgy.services.AddEmision testInput
    );
}
