package com.intelgy.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-11-07T11:28:58.671-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "TestWebServiceImplService", 
                  wsdlLocation = "classpath:wsdl/helloworld.wsdl",
                  targetNamespace = "http://services.intelgy.com/") 
public class TestWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.intelgy.com/", "TestWebServiceImplService");
    public final static QName TestWebServiceImplPort = new QName("http://services.intelgy.com/", "TestWebServiceImplPort");
    static {
        URL url = TestWebServiceImplService.class.getClassLoader().getResource("wsdl/helloworld.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TestWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/helloworld.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public TestWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TestWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort() {
        return super.getPort(TestWebServiceImplPort, TestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TestWebServiceImplPort, TestWebService.class, features);
    }

}
