apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "logscentralizados"
roleRef:
  # Add the view role to the service account
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "logscentralizados"
