PKG_WS_FXF.PRC_INSERTA_FD_TMOVIMIENTO(
  VARCHAR ${headers.auxi},
  VARCHAR ${headers.cias},
  VARCHAR ${headers.ciasDest},
  VARCHAR ${headers.descri},
  VARCHAR ${headers.encargo},
  VARCHAR ${headers.encargoDest},
  VARCHAR ${headers.entidad},
  DATE ${headers.fecha},
  VARCHAR ${headers.pFpago},
  VARCHAR ${headers.pOrpaVigencia},
  VARCHAR ${headers.pOrpaNumero},
  DOUBLE ${headers.pValor},
  VARCHAR ${headers.pGravamen},
  VARCHAR ${headers.pCuenta},
  OUT VARCHAR perrorOut,
  OUT VARCHAR vmovirenglonOut,
  VARCHAR ${headers.pMoviCtaDest},
  VARCHAR ${headers.pMoviTpctDest},
  VARCHAR ${headers.pMoviTpctPag},  
  VARCHAR ${headers.pFondo},
  VARCHAR ${headers.pTipoReg},
  OUT VARCHAR errnumOut,
  OUT VARCHAR descrOut
)