package fiduprod.wsfxf_wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-10-22T10:54:46.446-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "WsFXF", 
                  wsdlLocation = "file:/C:/Users/Entelgy/workspace/gatewaySaldoEncargos/src/main/resources/wsdl/WsFXF.wsdl",
                  targetNamespace = "http://fiduprod/WsFXF.wsdl") 
public class WsFXF_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fiduprod/WsFXF.wsdl", "WsFXF");
    public final static QName WsFXFPort = new QName("http://fiduprod/WsFXF.wsdl", "WsFXFPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Entelgy/workspace/gatewaySaldoEncargos/src/main/resources/wsdl/WsFXF.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsFXF_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Entelgy/workspace/gatewaySaldoEncargos/src/main/resources/wsdl/WsFXF.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsFXF_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsFXF_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsFXF_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WsFXF_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsFXF_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsFXF_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WsFXF
     */
    @WebEndpoint(name = "WsFXFPort")
    public WsFXF getWsFXFPort() {
        return super.getPort(WsFXFPort, WsFXF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsFXF
     */
    @WebEndpoint(name = "WsFXFPort")
    public WsFXF getWsFXFPort(WebServiceFeature... features) {
        return super.getPort(WsFXFPort, WsFXF.class, features);
    }

}
