package fiduprod.wsfxf_wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-10-22T10:54:46.416-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://fiduprod/WsFXF.wsdl", name = "WsFXF")
@XmlSeeAlso({fiduprod.wsfxf_wsdl.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsFXF {

    @WebMethod(action = "http://fiduprod/WsFXF.wsdl/prcFdInterfaz")
    @WebResult(name = "prcFdInterfazResponseElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/", partName = "prcFdInterfazResponseElement")
    public fiduprod.wsfxf_wsdl.types.PrcFdInterfazResponseElement prcFdInterfaz(
        @WebParam(partName = "prcFdInterfazElement", name = "prcFdInterfazElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/")
        fiduprod.wsfxf_wsdl.types.PrcFdInterfazElement prcFdInterfazElement
    );

    @WebMethod(action = "http://fiduprod/WsFXF.wsdl/prcFdValidarSaldo")
    @WebResult(name = "prcFdValidarSaldoResponseElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/", partName = "prcFdValidarSaldoResponseElement")
    public fiduprod.wsfxf_wsdl.types.PrcFdValidarSaldoResponseElement prcFdValidarSaldo(
        @WebParam(partName = "prcFdValidarSaldoElement", name = "prcFdValidarSaldoElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/")
        fiduprod.wsfxf_wsdl.types.PrcFdValidarSaldoElement prcFdValidarSaldoElement
    );

    @WebMethod(action = "http://fiduprod/WsFXF.wsdl/prcInsertaFdTmovimiento")
    @WebResult(name = "prcInsertaFdTmovimientoResponseElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/", partName = "prcInsertaFdTmovimientoResponseElement")
    public fiduprod.wsfxf_wsdl.types.PrcInsertaFdTmovimientoResponseElement prcInsertaFdTmovimiento(
        @WebParam(partName = "prcInsertaFdTmovimientoElement", name = "prcInsertaFdTmovimientoElement", targetNamespace = "http://fiduprod/WsFXF.wsdl/types/")
        fiduprod.wsfxf_wsdl.types.PrcInsertaFdTmovimientoElement prcInsertaFdTmovimientoElement
    );
}
